# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 991b3ed530376cfd9f0dbf507a729a0a601fa2cd40d8b7b2bce24e1ef6c1c6b52ea22a9eec00742ff4df76d56bf9fd2fb54d36c9d17269c0a5501cfeb04638b9

test:
  secret_key_base: dc94871897491d09a922e777502bcb3a63f2d72477b39a80c6556dcfecd6be514df0dfabae73c30eb20ceb0920828458461caba45de8346ecd9eb88ac6919253

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
